<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
Introduction and Problem Statement
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

Have you ever wondered how one sports team achieves success while another fails to do so?
    <br>
    
"The initial idea to answer this question is that the winning team is constantly engaged in intense and rigorous training — and that’s true!"
    <br>

However, training alone does not guarantee a team’s success; other factors also play a significant role. The importance of data-driven decision-making has become evident even in the world of sports. Coaches of top sports teams not only design regular and effective training programs for their players but also analyze their own team's performance and study the behavior and playing style of the opposing team to turn the game in their favor.
    <br>
    
One of the key analyses that top coaches perform is evaluating player performance. This allows them to recruit better players or even plan for the future by identifying and bringing in individuals who have the potential to shine in the coming years.
    <br>
    <br>
    <b>
   In this exercise, we aim to analyze the performance of players in the NBA (National Basketball Association) and predict whether a player will continue to play in the league for the next five years or not.
    </b>
</font>
</p>

<h5 align=center style="direction: rtl;text-align: center;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
Kobe Bryant's brilliance will be remembered forever!
</font>
</h5>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
Import libraries
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    First, import the required libraries.

</font>
</p>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
Introduction to the Dataset
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

The training data consists of 21 columns and 938 rows, with each row representing the information of a single player.
    <br>
    In the table below, we can see the dataframe columns along with their descriptions:
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|Column|Description|
|:------:|:---:|
|name|Player Name|
|gp|Number of games the player has participated in|
|min|Number of minutes the player has been on the court|
|pts|Average points scored by the player per game|
|fgm|Average field goals made during the game|
|fga|Average attempts to make field goals during the game|
|fg|Field goal percentage|
|3p_made|Average three-point field goals made per game|
|3pa|Average attempts to make three-point field goals per game|
|3p|Three-point field goal percentage|
|ftm|Average free throws made per game|
|fta|Average free throw attempts per game|
|ft|Free throw percentage|
|oreb|Average offensive rebounds|
|dreb|Average defensive rebounds|
|reb|Average total rebounds|
|ast|Average assists|
|stl|Average steals|
|blk|Average blocks|
|tov|Average turnovers|
|target_5yrs|Whether the player stays in the NBA for 5 years or not (target variable)|
    
</font>
</div>



<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
The test data contains 402 rows and 20 columns. It is clear that the test dataframe does not include the 'target_5yrs' column!<code>test</code> column<code>target_5yrs</code>
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
Read Datasets
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    Now, by running the cell below, read the dataset from the file.
    
</font>
</p>

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/ML/Quera_exercise/تحلیل NBA/nba_players_train.csv')
test = pd.read_csv('/content/drive/MyDrive/ML/Quera_exercise/تحلیل NBA/nba_players_test.csv')

train

,name,gp,min,pts,fgm,fga,fg,3p_made,3pa,3p,...,fta,ft,oreb,dreb,reb,ast,stl,blk,tov,target_5yrs
0,James Young,31,10.7,3.4,1.2,3.3,35.3,0.5,2.1,25.8,...,0.9,55.2,0.3,1.1,1.4,0.4,0.3,0.1,0.2,0
1,Michael Anderson,65,18.5,7.4,2.9,5.8,50.1,0.0,0.1,0.0,...,2.7,57.1,1.8,2.7,4.5,1.0,1.0,0.3,1.2,0
2,Kobe Bryant,71,15.5,7.6,2.5,5.9,41.7,0.7,1.9,37.5,...,2.3,81.9,0.7,1.2,1.9,1.3,0.7,0.3,1.6,1
3,Darrin Hancock,46,9.2,3.3,1.5,2.6,56.2,0.0,0.1,33.3,...,0.8,41.0,0.3,0.8,1.2,0.7,0.4,0.1,0.7,0
4,Brent Price,68,12.6,3.9,1.5,4.1,35.8,0.1,0.7,16.7,...,1.0,79.4,0.4,1.1,1.5,2.3,0.8,0.0,1.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,Terry Dehere,64,11.9,5.3,2.0,5.3,37.7,0.4,0.9,40.4,...,1.3,75.3,0.4,0.7,1.1,1.2,0.4,0.1,0.9,1
934,Jordan Hamilton,26,9.9,4.4,1.8,4.3,43.2,0.7,1.8,36.2,...,0.2,40.0,0.4,2.0,2.4,0.8,0.1,0.1,0.6,1
935,David Lee,67,16.9,5.1,2.0,3.4,59.6,0.0,0.0,0.0,...,1.8,57.7,1.6,2.9,4.5,0.6,0.5,0.3,0.8,0
936,Travis Mays,64,33.5,14.3,4.6,11.3,40.6,1.1,3.1,36.5,...,5.2,77.0,0.8,1.9,2.8,4.0,1.3,0.2,2.5,0
937,Ron Harper,82,37.4,22.9,9.0,19.7,45.5,0.2,1.1,21.3,...,6.9,68.4,2.1,2.7,4.8,4.8,2.5,1.0,4.2,1

In [ ]:
test

,name,gp,min,pts,fgm,fga,fg,3p_made,3pa,3p,ftm,fta,ft,oreb,dreb,reb,ast,stl,blk,tov
0,Trevor Booker,65,16.4,5.3,2.1,3.9,54.9,0.0,0.0,0.0,1.0,1.6,67.3,1.5,2.4,3.9,0.5,0.5,0.7,0.6
1,Marques Bragg,53,7.0,2.5,1.0,2.3,45.0,0.0,0.0,0.0,0.4,0.8,56.1,0.7,0.8,1.5,0.2,0.3,0.1,0.5
2,Brian Davis,68,5.5,1.9,0.6,1.9,31.7,0.0,0.0,33.3,0.7,1.0,73.5,0.3,0.5,0.8,0.3,0.2,0.1,0.3
3,Mark Davis,33,7.8,3.8,1.5,3.1,48.0,0.0,0.3,10.0,0.8,1.0,82.4,0.5,0.6,1.1,0.4,0.4,0.1,0.4
4,Ike Diogu,69,14.9,7.0,2.5,4.8,52.4,0.0,0.0,0.0,2.0,2.4,81.0,1.4,1.9,3.3,0.4,0.2,0.4,1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,Daniel Santiago,54,10.8,3.1,1.2,2.5,47.8,0.0,0.0,0.0,0.8,1.1,68.9,0.6,1.2,1.9,0.2,0.3,0.4,0.9
398,Taj Gibson,82,26.9,9.0,3.8,7.7,49.4,0.0,0.0,0.0,1.4,2.1,64.6,2.8,4.7,7.5,0.9,0.6,1.3,1.4
399,Roy Hinson,80,23.2,5.5,2.3,4.6,49.6,0.0,0.0,0.0,0.9,1.5,59.0,2.2,4.1,6.2,0.9,0.4,1.8,1.4
400,Loren Woods,60,8.6,1.8,0.6,1.6,34.4,0.0,0.0,0.0,0.7,1.0,73.3,0.8,1.3,2.0,0.4,0.3,0.6,0.6
401,Charles Smith,34,8.6,3.5,1.4,3.7,39.2,0.4,1.4,31.9,0.2,0.3,54.5,0.4,0.4,0.8,0.6,0.3,0.2,0.8

In [ ]:
train.describe()

,gp,min,pts,fgm,fga,fg,3p_made,3pa,3p,ftm,fta,ft,oreb,dreb,reb,ast,stl,blk,tov,target_5yrs
count,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000,938.000000
mean,59.923241,17.684222,6.851066,2.645416,5.919723,44.221215,0.251599,0.784861,19.397441,1.310021,1.835821,70.155117,1.008849,2.037633,3.046482,1.541898,0.615458,0.364286,1.195842,0.620469
std,17.603618,8.347835,4.393109,1.688528,3.613987,6.153205,0.396331,1.090037,16.413031,1.002625,1.339840,10.727330,0.774842,1.369418,2.063277,1.476722,0.403514,0.434226,0.725694,0.485529
min,11.000000,3.100000,0.900000,0.300000,0.800000,26.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,0.300000,0.000000,0.000000,0.000000,0.100000,0.000000
25%,47.000000,11.000000,3.700000,1.400000,3.300000,40.300000,0.000000,0.000000,0.000000,0.600000,0.900000,64.600000,0.400000,1.000000,1.500000,0.600000,0.300000,0.100000,0.700000,0.000000
50%,62.000000,16.050000,5.600000,2.100000,4.900000,44.200000,0.100000,0.300000,22.700000,1.000000,1.500000,71.200000,0.800000,1.700000,2.500000,1.100000,0.500000,0.200000,1.000000,1.000000
75%,77.000000,22.800000,8.800000,3.375000,7.500000,47.975000,0.400000,1.200000,32.875000,1.600000,2.300000,77.600000,1.400000,2.675000,4.000000,1.900000,0.800000,0.500000,1.500000,1.000000
max,82.000000,40.900000,24.300000,9.000000,19.800000,73.700000,2.300000,6.500000,100.000000,7.500000,10.200000,100.000000,5.300000,9.600000,13.900000,10.600000,2.500000,3.900000,4.400000,1.000000

In [ ]:
test.describe()

,gp,min,pts,fgm,fga,fg,3p_made,3pa,3p,ftm,fta,ft,oreb,dreb,reb,ast,stl,blk,tov
count,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000
mean,61.559701,17.485572,6.685821,2.591045,5.804975,44.048507,0.238308,0.765920,18.571393,1.268905,1.789552,70.639055,1.010697,1.998010,3.006468,1.570647,0.625622,0.378607,1.188308
std,16.998098,8.222831,4.276587,1.673371,3.548366,6.107226,0.352724,0.994151,15.179848,0.950995,1.283850,10.227831,0.783375,1.339072,2.047164,1.459763,0.424400,0.417079,0.716000
min,11.000000,4.300000,0.700000,0.300000,0.900000,23.800000,0.000000,0.000000,0.000000,0.100000,0.200000,33.300000,0.000000,0.200000,0.300000,0.000000,0.000000,0.000000,0.100000
25%,48.000000,10.700000,3.525000,1.400000,3.200000,39.825000,0.000000,0.100000,0.000000,0.600000,0.900000,64.900000,0.425000,1.000000,1.500000,0.600000,0.300000,0.100000,0.700000
50%,65.000000,16.350000,5.300000,2.050000,4.700000,43.800000,0.100000,0.300000,21.400000,1.000000,1.450000,71.400000,0.800000,1.700000,2.400000,1.200000,0.500000,0.200000,1.000000
75%,78.000000,22.975000,8.800000,3.400000,7.600000,47.700000,0.300000,1.100000,31.775000,1.600000,2.300000,77.500000,1.400000,2.600000,3.900000,2.000000,0.800000,0.500000,1.500000
max,82.000000,39.700000,28.200000,10.200000,19.800000,61.600000,1.600000,4.600000,66.700000,7.700000,9.100000,100.000000,4.300000,8.000000,12.300000,8.300000,2.500000,2.400000,4.200000

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 938 entries, 0 to 937
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         938 non-null    object
 1   gp           938 non-null    int64
 2   min          938 non-null    float64
 3   pts          938 non-null    float64
 4   fgm          938 non-null    float64
 5   fga          938 non-null    float64
 6   fg           938 non-null    float64
 7   3p_made      938 non-null    float64
 8   3pa          938 non-null    float64
 9   3p           938 non-null    float64
 10  ftm          938 non-null    float64
 11  fta          938 non-null    float64
 12  ft           938 non-null    float64
 13  oreb         938 non-null    float64
 14  dreb         938 non-null    float64
 15  reb          938 non-null    float64
 16  ast          938 non-null    float64
 17  stl          938 non-null    float64
 18  blk          938 non-null    float64
 19  tov          938 non-null    float64
 20  target_5yrs  938 non-null    int64
dtypes: float64(18), int64(2), object(1)
memory usage: 154.0+ KB

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     402 non-null    object
 1   gp       402 non-null    int64
 2   min      402 non-null    float64
 3   pts      402 non-null    float64
 4   fgm      402 non-null    float64
 5   fga      402 non-null    float64
 6   fg       402 non-null    float64
 7   3p_made  402 non-null    float64
 8   3pa      402 non-null    float64
 9   3p       402 non-null    float64
 10  ftm      402 non-null    float64
 11  fta      402 non-null    float64
 12  ft       402 non-null    float64
 13  oreb     402 non-null    float64
 14  dreb     402 non-null    float64
 15  reb      402 non-null    float64
 16  ast      402 non-null    float64
 17  stl      402 non-null    float64
 18  blk      402 non-null    float64
 19  tov      402 non-null    float64
dtypes: float64(18), int64(1), object(1)
memory usage: 62.9+ KB

In [ ]:
train.isnull().sum()

name           0
gp             0
min            0
pts            0
fgm            0
fga            0
fg             0
3p_made        0
3pa            0
3p             0
ftm            0
fta            0
ft             0
oreb           0
dreb           0
reb            0
ast            0
stl            0
blk            0
tov            0
target_5yrs    0
dtype: int64

In [ ]:
test.isnull().sum()

name       0
gp         0
min        0
pts        0
fgm        0
fga        0
fg         0
3p_made    0
3pa        0
3p         0
ftm        0
fta        0
ft         0
oreb       0
dreb       0
reb        0
ast        0
stl        0
blk        0
tov        0
dtype: int64

In [ ]:
train.value_counts(train['target_5yrs'])

target_5yrs
1    582
0    356
Name: count, dtype: int64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
Preprocessing and Feature Engineering
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

In this question, you can use any preprocessing or feature engineering techniques that you have learned in previous chapters.
    <br>

The techniques you use will not be directly evaluated by the grading system. However, all of them will affect the accuracy of your model. Therefore, the better preprocessing and feature engineering you perform to improve the model’s accuracy, the higher the score you will earn for this question.
</font>
</p>

In [ ]:
train = train.drop(['name'], axis=1)
test = test.drop(['name'], axis=1)

In [ ]:
from sklearn.model_selection import train_test_split

X = train.drop(['target_5yrs'], axis=1)
y = train['target_5yrs']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=1)

In [ ]:
#adjusting indexes
X_train = X_train.reset_index(drop=True)
X_val = X_val.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
y_val = y_val.reset_index(drop=True)

In [ ]:
from sklearn.preprocessing import StandardScaler

X = train.drop(['target_5yrs'], axis=1)
y = train['target_5yrs']

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)
test = sc.transform(test)

In [ ]:
X_train = pd.DataFrame(X_train,columns=X.columns)

train = pd.concat([X_train, y_train], axis=1)
train

,gp,min,pts,fgm,fga,fg,3p_made,3pa,3p,ftm,fta,ft,oreb,dreb,reb,ast,stl,blk,tov,target_5yrs
0,0.831345,-0.031097,-0.007552,0.068053,-0.108797,0.876625,-0.640077,-0.635193,-1.167310,0.077402,0.398576,-1.119887,0.479685,-0.337527,-0.044665,-0.369800,0.174767,-0.174666,-0.021639,1
1,1.233691,-0.115644,-0.121000,-0.226172,-0.136181,-0.490487,-0.640077,-0.635193,-1.167310,0.574786,0.398576,0.572290,-0.559910,-0.630105,-0.628847,1.204526,1.151797,-0.853066,0.526551,1
2,-1.065427,-0.900721,-0.824377,-0.814622,-0.875556,0.109709,0.668748,0.318139,1.381754,-1.016843,-1.087102,-0.478348,-1.209657,-0.776394,-0.969619,-0.643595,-1.046520,-0.174666,-0.980971,1
3,0.429000,-0.188113,-0.710929,-0.638087,-0.464792,-0.973977,-0.116547,0.318139,-0.018436,-1.016843,-1.087102,-0.515538,0.089837,-0.044948,0.004016,-0.438249,-0.802262,0.051467,-0.706876,0
4,0.831345,1.563214,0.673135,0.774193,0.740115,0.326446,-0.640077,-0.730527,-1.167310,0.574786,0.918563,-0.831659,1.909129,2.661403,2.438105,0.109343,2.861600,3.443466,0.937693,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
698,-1.640206,-0.320972,-0.143690,0.068053,-0.218334,1.510164,-0.640077,-0.635193,-1.167310,-0.519459,-0.418547,-0.682897,0.869534,1.052221,1.026333,-0.780493,-0.313748,0.277600,-0.295734,0
699,-1.237861,-0.586691,-0.552102,-0.579242,-0.546945,-0.273750,0.930513,0.890139,0.974861,-0.817889,-0.864250,0.051620,-0.819809,-0.556960,-0.677528,-0.096004,-0.313748,-0.400800,-0.843923,1
700,1.118735,2.022182,3.032851,2.716077,3.040391,-0.207061,1.192278,1.748138,0.556001,3.559092,2.775660,1.622927,-0.170062,1.052221,0.588198,0.588486,0.907540,1.182133,2.308167,1
701,-0.778037,-1.045659,-0.983204,-1.050002,-0.820787,-2.141024,0.145218,0.127473,0.597887,-0.917366,-0.938534,0.051620,-0.689860,-0.483816,-0.580165,-0.712044,-0.802262,-0.400800,-0.980971,1
702,0.543956,-1.045659,-1.119342,-1.108847,-1.204167,0.743248,-0.640077,-0.730527,4.816408,-0.917366,-1.012818,0.042322,0.089837,-0.703250,-0.434119,-0.848942,-1.290777,-0.626933,-1.118018,1

In [ ]:
X_val = pd.DataFrame(X_val,columns=X.columns)

val = pd.concat([X_val, y_val], axis=1)
val

,gp,min,pts,fgm,fga,fg,3p_made,3pa,3p,ftm,fta,ft,oreb,dreb,reb,ast,stl,blk,tov,target_5yrs
0,1.003779,0.536574,1.331133,1.421488,0.630578,2.843932,-0.640077,-0.730527,-1.167310,1.370601,1.735686,-0.524836,1.129432,1.344800,1.367106,-0.232902,-0.313748,1.634400,1.759977,1
1,-1.065427,-0.369284,-0.211759,-0.461552,-0.382639,-0.540503,1.715808,1.462138,1.154372,-0.022075,-0.344263,1.873965,-1.079708,-0.776394,-0.920937,-0.438249,-0.802262,-0.853066,-0.980971,1
2,-0.433169,-0.502144,-0.642861,-0.638087,-0.546945,-0.507159,-0.640077,-0.635193,0.825268,-0.519459,-0.492831,-0.143631,-1.079708,-0.849539,-0.969619,0.725384,-0.313748,-0.626933,-0.295734,1
3,0.773867,-0.308894,-0.393275,-0.402707,-0.355255,-0.340438,0.406983,0.890139,0.292717,-0.419982,-0.418547,-0.264501,-0.689860,-0.264382,-0.434119,-0.369800,-0.313748,-0.174666,-0.295734,0
4,-1.065427,-0.357206,-0.642861,-0.579242,-0.245718,-1.890942,-0.378312,-0.063194,-0.168029,-0.718412,-0.789966,0.479313,-1.079708,-0.776394,-0.920937,0.040894,-0.313748,-0.400800,-0.158686,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,-0.663081,0.355402,0.446239,0.597658,0.247198,1.443476,-0.640077,-0.444527,-0.311639,0.276356,0.844279,-1.649855,1.519281,1.052221,1.269742,-0.506697,-0.313748,1.634400,0.663598,1
231,-0.950471,-1.383846,-1.028583,-0.991157,-1.122014,1.576853,-0.640077,-0.730527,-1.167310,-0.917366,-0.864250,-1.845106,-0.819809,-0.776394,-0.823574,-0.917391,-1.046520,0.051467,-0.843923,1
232,-1.467772,-1.226831,-1.073963,-1.050002,-1.204167,1.393460,-0.640077,-0.635193,-1.167310,-0.817889,-0.789966,-1.361627,-0.689860,-0.630105,-0.677528,-0.917391,-1.290777,-0.626933,-1.118018,0
233,0.658911,2.336213,2.987472,2.774922,2.793933,0.259757,0.668748,1.176138,0.358538,3.459615,3.444215,0.460718,-0.170062,1.710523,1.075015,2.915750,2.128827,0.051467,2.445214,1
234,-1.352817,-1.118128,-1.096652,-1.050002,-0.957708,-1.324091,-0.378312,-0.158527,-0.030404,-1.116320,-1.161386,-0.292394,-0.559910,-0.776394,-0.774892,-0.848942,-1.046520,-0.853066,-1.118018,0

In [ ]:
X = train.drop(['target_5yrs'], axis=1)
test = pd.DataFrame(test,columns=X.columns)
test

,gp,min,pts,fgm,fga,fg,3p_made,3pa,3p,ftm,fta,ft,oreb,dreb,reb,ast,stl,blk,tov
0,0.256566,-0.176035,-0.370586,-0.343862,-0.574329,1.776918,-0.640077,-0.730527,-1.167310,-0.320505,-0.195695,-0.236608,0.609635,0.247630,0.393471,-0.712044,-0.313748,0.729867,-0.843923
1,-0.433169,-1.311377,-1.005894,-0.991157,-1.012477,0.126381,-0.640077,-0.730527,-1.167310,-0.917366,-0.789966,-1.277948,-0.429961,-0.922684,-0.774892,-0.917391,-0.802262,-0.626933,-0.980971
2,0.429000,-1.492549,-1.142031,-1.226537,-1.122014,-2.091008,-0.640077,-0.730527,0.825268,-0.618936,-0.641398,0.339848,-0.949758,-1.142117,-1.115664,-0.848942,-1.046520,-0.626933,-1.255066
3,-1.582728,-1.214752,-0.710929,-0.696932,-0.793403,0.626543,-0.640077,-0.444527,-0.568938,-0.519459,-0.641398,1.167341,-0.689860,-1.068973,-0.969619,-0.780493,-0.558005,-0.626933,-1.118018
4,0.486478,-0.357206,0.015137,-0.108482,-0.327871,1.360115,-0.640077,-0.730527,-1.167310,0.674263,0.398576,1.037174,0.479685,-0.118093,0.101380,-0.780493,-1.046520,0.051467,-0.158686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,-0.375692,-0.852409,-0.869756,-0.873467,-0.957708,0.593199,-0.640077,-0.730527,-1.167310,-0.519459,-0.567115,-0.087845,-0.559910,-0.630105,-0.580165,-0.917391,-0.802262,0.051467,-0.432781
398,1.233691,1.092167,0.468929,0.656503,0.466272,0.859953,-0.640077,-0.730527,-1.167310,0.077402,0.175724,-0.487645,2.298977,1.929957,2.146014,-0.438249,-0.069490,2.086666,0.252456
399,1.118735,0.645277,-0.325207,-0.226172,-0.382639,0.893297,-0.640077,-0.730527,-1.167310,-0.419982,-0.269979,-1.008315,1.519281,1.491089,1.513151,-0.438249,-0.558005,3.217333,0.252456
400,-0.030824,-1.118128,-1.164721,-1.226537,-1.204167,-1.640861,-0.640077,-0.730527,-1.167310,-0.618936,-0.641398,0.321253,-0.300011,-0.556960,-0.531483,-0.780493,-0.802262,0.503734,-0.843923
401,-1.525250,-1.118128,-0.778998,-0.755777,-0.629097,-0.840601,0.406983,0.604139,0.741496,-1.116320,-1.161386,-1.426711,-0.819809,-1.215262,-1.115664,-0.643595,-0.802262,-0.400800,-0.569829

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
Modeling
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    Now that you have cleaned the data and possibly added or removed some features, it is time to train a model that can predict the target variable of this problem.
    
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    الگوریتم <i>رگرسیون لجستیک</i> با نام <code>LogisticRegression</code> در پکیج <code>linear_model</code> این کتابخانه در دسترس است. برخی از آرگومان‌های مهم آن در جدول زیر آمده است، اما جهت مطالعه‌ی کامل‌تر مستندات می‌توانید به <a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html" target="_blank">این لینک</a> مراجعه فرمایید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|آرگومان|جنس و تایپ|توضیحات|
|:------:|:--------:|:---:|
|penalty|<code>str</code> یا <code>None</code>|هایپرپارامتری است که برای جلوگیری از بیش‌برازش استفاده می‌شود. اگر None نباشد، به تابع هزینه مقادیری را اضافه می‌کند تا در فرایند بهینه‌سازی، وزن بعضی از متغیرها بیشتر کاهش یابد. <code>None</code>, <code>l1</code>, <code>l2</code>, <code>elasticnet</code> مقادیری است که این آرگومان می‌پذیرد. با جزئیات کاری که این هایپرپارامتر انجام می‌هد در درسنامه‌های بعدی آشنا می‌شوید|
|fit_intercept|<code>bool</code>|مشخص می‌کند که آیا الگوریتم با بایاس آموزش ببیند یا خیر|
|class_weight|<code>str</code> یا <code>dict</code>|وزنی که هر کلاس در فرایند آموزش دارد را با این آرگومان می‌توان تنظیم کرد. کارایی این هایپرپارامتر جایی مشخص می‌شود که تعداد نمونه‌های هر کلاس، متعادل نباشد. مثلا تعداد بیماران سرطانی در برابر همه کسانی که به بیمارستان مراجعه می‌کنند. با تظیم این آرگومان می‌توان به کلاس‌ها وزن داد به شکلی که اگر مدل در پیشبینی نمونه‌های آن کلاس دچار خطا شد، بیشتر از حالت معمول جریمه شود. اگر None باشد، وزن همه کلاس‌ها برابر ۱ خواهد بود. اگر رشته <code>balanced</code> پاس داده شود، از فرمول $$n\_samples / (n\_classes * np.bincount(y))$$ استفاده می‌شود. دیکشنری را می‌توان به شکل <code>{class_label:class_weight}</code> به این آرگومان پاس داد|
|max_iter|<code>int</code>|حداکثر دفعاتی که الگوریتم بهینه‌ساز مجاز است اجرا شود تا به نقطه بهینه همگرا شود|
|n_jobs|<code>int</code>|تعداد <i>core</i>های cpu که در فرایند موازی‌سازی استفاده شود را مشخص می‌کند. اگر برابر ۱- تنظیم شود، از همه <i>core</i>ها استفاده خواهد کرد|
    
</font>
</div>
</center>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
آموزش مدل
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در سلول زیر با استفاده از مدل آماده‌ای که در بالا شرح داده شد و به کمک تابع <code>fit</code> الگوریتم را بر روی دادگان آموزشی اجرا کنید.
</font>
</p>

In [ ]:
# modeling
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = train.drop(columns = ['target_5yrs'])
y = train['target_5yrs']


# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_val)
y_pred

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0])

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>roc_auc_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazirmatn" size=3>در درسنامه بعدی کالج و در ادامه بررسی معیارهای ارزیابی الگوریتم‌های دسته‌بند، به معرفی کامل AUC-ROC خواهیم پرداخت.</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazirmatn" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>65%</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

In [ ]:
# evaluate model
from sklearn.metrics import roc_auc_score
print('roc= ',roc_auc_score(y_val,y_pred) * 100)

roc=  67.19858156028369

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|------|---|
|target_5yrs|آیا بازیکن ۵ سال در لیگ حرفه‌ای بازی خواهد کرد با خیر|
    
</font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    اسم دیتافریم باید <i>submission</i> باشد؛ در غیر این صورت، سامانه داوری نمی‌تواند تلاش‌ شما را ارزیابی کند.
    <br>
    این دیتافریم تنها شامل ۱ ستون با اسم <i>target_5yrs</i> است و ۴۰۲ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <i>test</i> شما باید یک مقدار پیشبینی شده داشته باشید.
    <br>
    جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، اعداد ستون <i>target_5yrs</i> ممکن است متفاوت باشد.
</font>
</p>

<div style="text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
||target_5yrs|
|----|-----|
|0|1|
|1|1|
|2|0|
|3|1|
|4|0|

</font>
</div>

In [ ]:
# modeling
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(test)

In [ ]:
# predict test samples
submission = pd.DataFrame(y_pred, columns = ['target_5yrs'])
submission

     target_5yrs
0              1
1              0
2              1
3              0
4              1
..           ...
397            0
398            1
399            1
400            1
401            0

[402 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <i>result.zip</i> سلول زیر را اجرا کنید.
</font>
</p>

In [ ]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)



joblib.dump(model, 'model')
submission.to_csv('submission.csv', index=False)

file_names = ['model', 'submission.csv', 'nba_analysis.ipynb']
compress(file_names)